### ISSUE TITLE
Missing dependency (RPi::WiringPi::Constant)

### ISSUE THREAD

**Issue by fhelmberger** [stevieb9/rpi-spi#2]
Installation fails if RPi::WiringPi::Constant isn't already installed.

**Comment by stevieb9** [comment]
Can you please advise on exactly how and what you were attempting to install? I can not reproduce the issue when installing `RPi::SPI`.

**Comment by fhelmberger** [comment]
I tried to install RPI::SPI on a fresh brewed Perl 5.24 on latest Raspbian.

Installation failed because RPi::WiringPi::Constant wasn't already installed. After installing RPi::WiringPi::Constant manually RPI:SPI installed without problems.

Adding RPi::WiringPi::Constant to the list of required modules should fix this.

**Comment by stevieb9** [comment]
The strange thing here is that `RPi::SPI` nor its only dependency don't have any code that uses `RPi::WiringPi::Constant`, so I'm quite confused. The only mention of that distribution is within two files in the `test` directory, but I can't reproduce the error you're getting whether by installing from CPAN, or from Github.

Still trying to sort out where that's coming from.

**Comment by fhelmberger** [comment]
I just checked the cpanm logs again, I had the problem in RPI::LCD not RPI::SPI. Sorry for the mistake!

**Comment by fhelmberger** [comment]
Just checked Makefile.PL of RPi::LCD in your github repo. It's already listed in PREREQ_PM. 
So the problem was that the version on cpan is the one without that change.
Sorry for the buzz, I guess we can close this issue. Thanks for your time!
