### ISSUE TITLE
error when using optional speed parameter

### ISSUE THREAD

**Issue by gnotoix** [stevieb9/rpi-spi#5]
I found a copy&paste error in the constructor of PRi::SPI.
The channel-setter is called for the speed-parameter.
Please see attached patch-file !
[SPI.pm.patch.txt](https://github.com/stevieb9/rpi-spi/files/1699895/SPI.pm.patch.txt)

**Comment by stevieb9** [comment]
Nice catch! Thanks for the patch. I'll apply ASAP.
